#!/usr/bin/with-contenv bash

# create folders
mkdir -p /var/log/sonarrannounced

# install or update app
if [[ -d "/config/sonarrAnnounced/.git" ]]; then
  cd "/config/sonarrAnnounced/" && git pull --rebase
else
  git clone https://github.com/fryfrog/sonarrAnnounced.git /config/sonarrAnnounced
fi

# install requirements
pip3 install -r /config/sonarrAnnounced/requirements.txt

# copy default config in place if missing
if [[ ! -f /config/sonarrAnnounced/settings.cfg ]]; then
  cp /config/sonarrAnnounced/settings.cfg.default /config/sonarrAnnounced/settings.cfg
fi

# link log and settings into /config
if [[ ! -L /config/settings.cfg ]]; then
  ln -sf /config/sonarrAnnounced/settings.cfg /config
fi

if [[ ! -L /config/status.log ]]; then
  ln -sf /config/sonarrAnnounced/status.log /config
fi

# permissions
chown -R abc:abc /config
chmod 775 /var/log/sonarrannounced
