#!/usr/bin/with-contenv bash

# create folders
mkdir -p /var/log/sonarrannounced

# install app
[[ ! -d "/config/.git" ]] && \
  git clone https://github.com/fryfrog/sonarrAnnounced.git /config

pip3 install -r /config/requirements.txt

if [[ ! -f /config/settings.cfg ]]; then
  cp /config/settings.cfg.default /config/settings.cfg
fi

# permissions
chown -R abc:abc /config

chmod 777 /var/log/sonarrannounced
