#!/usr/bin/with-contenv bash

# create folders
mkdir -p /var/log/sonarrannounced

# install app
[[ ! -d "/config/sonarrAnnounced/.git" ]] && \
  git clone https://github.com/fryfrog/sonarrAnnounced.git /config/sonarrAnnounced

pip3 install -r /config/sonarrAnnounced/requirements.txt

if [[ ! -f /config/sonarrAnnounced/settings.cfg ]]; then
  cp /config/sonarrAnnounced/settings.cfg.default /config/sonarrAnnounced/settings.cfg
fi

# permissions
chown -R abc:abc /config
chmod 775 /var/log/sonarrannounced
